### ISSUE TITLE
Let'sEncrypt 문서의 양이 너무 큽니다.

### ISSUE THREAD

**Issue by schbal** [HAKorea/gitpages_source#14]
https://hakorea.github.io/docs/ecosystem/certificates/lets_encrypt/
해당 문서 링크입니다.

유난히 해당 문서에서는 스크롤의 압박이 느껴집니다. 용량보니까 무려 30KB나 되네요.
일단 왜그런지 살펴보겠습니다🤔 다음은 문서의 목차만 번역한 내용입니다.

목차:
 - 0 - IP 주소, 포트 번호 및 포트포워딩에 대한 기본적인 수준의 이해
 - 1 - 장치가 고정 IP 주소를 가지도록 설정
 - 2 - (TLS/SSL 없이)포트포워딩, 그리고 연결 테스트
 - 3 - DuckDNS 계정 설정
 - 4 - Let's Encrypt에서 TLS/SSL 인증서 발급
 - 5 - 들어오는 연결 확인
 - 6 - 포트포워딩 정리
 - 7 - 인증서 만료 날짜를 모니터링하도록 센서 설정
 - 8 - TLS/SSL 인증서의 자동 재발급 설정
 - 9 - 문제 발생 시 경고 알림 설정

제목에도 나와있듯이 Let'sEncrypt 인증서를 발급하는 내용이 담길 문서입니다.
하지만 이 문서에서는 IP와 포트, 포트포워딩의 개념부터 고정IP 설정, 도메인 발급뒤 연결까지 설명하고 있네요. 
같은 네트워크라는 범주에 속한다 해도, tls인증서 발급이라는 주제와는 격차가 큰 내용들이 많습니다.
특히 목차 0, 1, 2는 적당한 곳에 있으면 빛을 발할 내용같네요

**Comment by zooil** [comment]
좋은 의견이네요. 그런데 이게 공식홈의 문서와 달리 분리를 해버리면 공식홈이 업데이트 될때 버전이 달라질 수 있습니다. 별도로 오른쪽에 인덱스를 추가할 수 있는지 고려해보겠습니다.

**Comment by minsuke** [comment]
Let's encrypt가 IOT 보안을 위해서 무척이나 필요한 내용인데, 문서 내용이 방대하군요. 의견 감사합니다.

**Comment by zooil** [comment]
의견 주신대로 파일 두개로 분리했습니다.
https://hakorea.github.io/docs/ecosystem/certificates/lets_encrypt2/index.html

**Comment by schbal** [comment]
작업에 감사드립니다
이제 제자리를 찾은것같네요 ㅎㅎ

그럼 이슈는 닫겠습니다
